home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotel.urls')),
    path('', include('login.urls')),
    path('RumahSakit/',include('dokter.urls')),
    path('', include('trigger6.urls')),
    path('pasien/', include('pasien.urls')),
    path('', include('trigger3.urls')),
]

trigger3/urls.py
from django.urls import path

from . import views

app_name = 'trigger3'

urlpatterns = [
    path('list_reservasi_rs/', views.read_reservasi_rs, name='list_reservasi_rs'),
    path('create_reservasi_rs/', views.create_reservasi_rs, name='create_reservasi_rs'),
    path('get_ruangan_of_rs/', views.get_ruangan_of_rs, name='get_ruangan_of_rs'),
    path('get_bed_of_rs', views.get_bed_of_rs, name='get_bed_of_rs'),
    path('delete_reservasi_rs/<int:kodepasien>/<slug:tglmasuk>', views.delete_reservasi_rs, name='delete_reservasi_rs'),
    path('update_reservasi_rs/<int:kodepasien>/<slug:tglmasuk>', views.update_reservasi_rs, name='update_reservasi_rs'),
    path('list_faskes/', views.read_faskes, name='read_faskes'),
    path('detail_faskes/<slug:kode>/', views.detail_faskes, name='detail_faskes'),
    path('create_faskes/', views.create_faskes, name='create_faskes'),
    path('delete_faskes/<slug:kode>/', views.delete_faskes, name='delete_faskes'),
    path('update_faskes/<slug:kode>/', views.update_faskes, name='update_faskes'),
    path('create_jadwal_faskes/', views.create_jadwal_faskes, name='create_jadwal_faskes'),
    path('list_jadwal_faskes/', views.read_jadwal_faskes, name='read_jadwal_faskes'),
    path('create_rs/', views.create_rs, name='create_rs'),
    path('list_rs/', views.read_rs, name='read_rs'),
    path('update_rs/<slug:kodefaskes>/', views.update_rs, name='update_rs'),
    path('list_transaksi_rs/', views.read_transaksi_rs, name='read_transaksi_rs'),
    path('update_transaksi_rs/<slug:idtransaksi>', views.update_transaksi_rs, name='update_transaksi_rs'),
    path('delete_transaksi_rs/<slug:idtransaksi>', views.delete_transaksi_rs, name='delete_transaksi_rs')
]

trigger3/models.py
from django.db import models

# Create your models here.

trigger3/views.py
from django.shortcuts import redirect, render
from django.db import connection
from collections import namedtuple
from django.contrib import messages

from login.views import namedtuplefetchall, dictfetchone, dictfetchall
from django.http import JsonResponse

import datetime

###########
# NOMOR 7 #
###########

def create_reservasi_rs(request):
    if request.session['role'] == 'SATGAS':
        if request.method == 'GET':
            c = connection.cursor()
            c.execute('SELECT kode_faskes FROM RUMAH_SAKIT')
            list_rs = namedtuplefetchall(c)
            c.execute('SELECT nik FROM PASIEN')
            list_pasien = namedtuplefetchall(c)
            return render(request, 'reservasi_rs_create.html', {'list_rs': list_rs, 'list_pasien': list_pasien})

        elif request.method == 'POST':
            form = request.POST
            nik_pasien = form.get('nikpasien')
            tgl_masuk = form.get('tglmasuk')
            tgl_keluar = form.get('tglkeluar')
            kode_rs = form.get('koders')
            kode_ruangan = form.get('koderuangan')
            kode_bed = form.get('kodebed')

            # Mengurus tanggal
            tm_split = tgl_masuk.split('-')
            tgl_masuk = tm_split[2] + '-' + tm_split [1] + '-' + tm_split[0] + ' 00:00:00'
            tk_split = tgl_keluar.split('-')
            tgl_keluar = tk_split[2] + '-' + tk_split [1] + '-' + tk_split[0] + ' 23:59:59'

            c = connection.cursor()
            c.execute('''
                INSERT INTO RESERVASI_RS(kodepasien, tglmasuk, tglkeluar, koders, koderuangan, kodebed)
                VALUES({}, '{}', '{}', '{}', '{}', '{}')
            '''.format(nik_pasien, tgl_masuk, tgl_keluar, kode_rs, kode_ruangan, kode_bed))

            return redirect('/list_reservasi_rs')

    return redirect('/')
    
# Create reservasi rs ajax functions
def get_ruangan_of_rs(request):
    arg = request.GET['q']
    print(arg)
    c = connection.cursor()
    c.execute('''
    SELECT koderuangan FROM RUANGAN_RS WHERE koders='{}'
    '''.format(arg))
    
    data = namedtuplefetchall(c)

    return JsonResponse(data, safe=False)

def get_bed_of_rs(request):
    arg = request.GET['q']
    c = connection.cursor()
    c.execute('''
    SELECT kodebed FROM BED_RS WHERE koders='{}'
    '''.format(arg))
    
    data = namedtuplefetchall(c)

    return JsonResponse(data, safe=False)

def read_reservasi_rs(request):
    if request.session['role'] == 'SATGAS':
        c = connection.cursor()
        c.execute('SELECT * FROM RESERVASI_RS')
        return render(request, 'reservasi_rs_read.html', {'reservasi_rs': namedtuplefetchall(c)})
        
    elif request.session['role'] == 'PENGGUNA_PUBLIK':
        username = request.session['username']
        print(username)
        c = connection.cursor()
        c.execute('''
            SELECT * FROM RESERVASI_RS WHERE kodepasien IN
            (SELECT nik FROM PASIEN WHERE idpendaftar = '{}')
        '''.format(username))
        return render(request, 'reservasi_rs_read.html', {'reservasi_rs': namedtuplefetchall(c)})
    
    return redirect('/')

def update_reservasi_rs(request, kodepasien, tglmasuk):
    if request.session['role'] == 'SATGAS':
        if request.method == 'GET':
            c = connection.cursor()
            c.execute('''
                SELECT * FROM RESERVASI_RS
                WHERE kodepasien = '{}'
                AND tglmasuk = '{}'
            '''.format(kodepasien, tglmasuk))
            # print(namedtuplefetchall(c))
            return render(request, 'reservasi_rs_update.html', {'data':namedtuplefetchall(c)})
        
        elif request.method == 'POST':
            form = request.POST
            tgl_keluar = form.get('tglkeluar')

            # Mengurus tanggal
            tk_split = tgl_keluar.split('-')
            tgl_keluar = tk_split[2] + '-' + tk_split [1] + '-' + tk_split[0] + ' 23:59:59'

            c = connection.cursor()
            c.execute('''
                UPDATE RESERVASI_RS
                SET tglkeluar = '{}'
                WHERE kodepasien = '{}'
                AND tglmasuk = '{}'
            '''.format(tgl_keluar, kodepasien, tglmasuk))

            return redirect('/list_reservasi_rs')
    return redirect('/')

def delete_reservasi_rs(request, kodepasien, tglmasuk):
    if request.session['role'] == 'SATGAS':
        tm_split = tglmasuk.split()[0].split('-')
        tgl_masuk = datetime.datetime(int(tm_split[0]), int(tm_split[1]), int(tm_split[2]))

        if tgl_masuk > datetime.datetime.now():
            c = connection.cursor()
            c.execute('''
                DELETE FROM RESERVASI_RS
                WHERE kodepasien = '{}'
                AND tglmasuk = '{}'
            '''.format(kodepasien, tglmasuk))

            c.execute('SELECT * FROM RESERVASI_RS')
            data = {
                'reservasi_rs': namedtuplefetchall(c)
            }
            return redirect('/list_reservasi_rs')

        else:
            c = connection.cursor()
            c.execute('SELECT * FROM RESERVASI_RS')
            data = {
                'message': 'Reservasi tidak bisa dihapus',
                'reservasi_rs': namedtuplefetchall(c)
            }
            return render(request, 'reservasi_rs_read.html', data)
    
    return redirect('/')

###########
# NOMOR 8 #
###########

def create_faskes(request):
    if request.session['role'] == 'SATGAS':
        if request.method == 'GET':
            c = connection.cursor()
            c.execute('''
                SELECT kode FROM FASKES ORDER BY kode DESC LIMIT 1
            ''')

            last_kode = str(dictfetchone(c).get('kode'))
            kode_split = []

            for i in range(len(last_kode)):
                kode_split.append(last_kode[i])
            
            kode_split.remove('F')

            last_num = int(''.join(kode_split))
            last_num += 1

            new_kode = 'F' + f"{last_num:02}"

            data = {
                'new_kode': new_kode
            }

            return render(request, 'faskes_create.html', data)

        elif request.method == 'POST':
            form = request.POST
            kode = form.get('kode')
            tipe = form.get('tipe')
            nama = form.get('nama')
            statusmilik = form.get('statusmilik')
            jalan = form.get('jalan')
            kelurahan = form.get('kelurahan')
            kecamatan = form.get('kecamatan')
            kabkot = form.get('kabkot')
            prov = form.get('prov')

            c = connection.cursor()
            c.execute('''
                INSERT INTO FASKES VALUES (
                    '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}'
                )
            '''.format(kode, tipe, nama, statusmilik, jalan, kelurahan, kecamatan, kabkot, prov))

            return redirect('/list_faskes')
    
    return redirect('/')

def read_faskes(request):
    if request.session['role'] == 'SATGAS':
        c = connection.cursor()
        c.execute('SELECT * FROM FASKES')

        data = {
            'list_faskes': dictfetchall(c)
        }

        return render(request, 'faskes_read.html', data)
    
    return redirect('/')

def detail_faskes(request, kode):
    if request.session['role'] == 'SATGAS':
        c = connection.cursor()
        c.execute('''
            SELECT * FROM FASKES
            WHERE kode = '{}'
        '''.format(kode))

        data = {
            'data': dictfetchone(c)
        }

        return render(request, 'faskes_detail.html', data)
    
    return redirect('/')

def update_faskes(request, kode):
    if request.session['role'] == 'SATGAS':
        if request.method == 'GET':
            c = connection.cursor()
            c.execute('''
                SELECT * FROM FASKES
                WHERE kode = '{}'
            '''.format(kode))

            data = {
                'data': dictfetchone(c)
            }

            return render(request, 'faskes_update.html', data)

        elif request.method == 'POST':
            form = request.POST
            kode = form.get('kode')
            tipe = form.get('tipe')
            nama = form.get('nama')
            statusmilik = form.get('statusmilik')
            jalan = form.get('jalan')
            kelurahan = form.get('kelurahan')
            kecamatan = form.get('kecamatan')
            kabkot = form.get('kabkot')
            prov = form.get('prov')

            c = connection.cursor()
            c.execute('''
                UPDATE FASKES
                SET (tipe, nama, statusmilik, jalan, kelurahan, kecamatan, kabkot, prov) =
                ('{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}')
                WHERE kode = '{}'
            '''.format(tipe, nama, statusmilik, jalan, kelurahan, kecamatan, kabkot, prov, kode))

            return redirect('/list_faskes')

    return redirect('/')

def delete_faskes(request, kode):
    if request.session['role'] == 'SATGAS':
        c = connection.cursor()
        c.execute('''
            DELETE FROM FASKES
            WHERE kode='{}'
        '''.format(kode))
        return redirect('/list_faskes')
    
    return redirect('/')

###########
# NOMOR 9 #
###########

def create_jadwal_faskes(request):
    if request.session['role'] == 'SATGAS':
        if request.method == 'GET':
            c = connection.cursor()
            c.execute('SELECT kode FROM FASKES')

            data = {
                'list_kode': dictfetchall(c)
            }

            return render(request, 'jadwal_faskes_create.html', data)

        elif request.method == 'POST':
            form = request.POST
            kodefaskes = form.get('kodefaskes')
            shift = form.get('shift')
            tanggal = form.get('tanggal')

            # Mengurus tanggal
            tgl_split = tanggal.split('-')
            tanggal = tgl_split[2] + '-' + tgl_split [1] + '-' + tgl_split[0]

            c = connection.cursor()
            c.execute('''

trigger3/templates/faskes_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
{% endblock %}

{% block title %} Create Faskes {% endblock %}

{% block body %}
<div class="card m-3">
    <h3 class="card-header"> Create Faskes </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="kode" class="form-label">Kode Faskes</label>
                    <input required readonly="readonly" type="text" name="kode" class="form-control " id="kode" value="{{ new_kode }}">
                </div>

                <div class="mb-3">
                    <label for="tipe" class="form-label">Tipe</label>
                    <input required type="text" name="tipe" class="form-control " id="tipe">
                </div>

                
                <div class="mb-3">
                    <label for="nama" class="form-label">Nama Faskes</label>
                    <input required type="text" name="nama" class="form-control " id="nama">
                </div>
                
                <div class="mb-3">
                    <label for="statusmilik" class="form-label">Status Kepemilikan</label>
                    <input required type="text" name="statusmilik" class="form-control " id="statusmilik">
                </div>

                <h3>Alamat</h3>

                <div class="mb-3">
                    <label for="jalan" class="form-label">Jalan</label>
                    <input required type="text" name="jalan" class="form-control " id="jalan">
                </div>

                <div class="mb-3">
                    <label for="kelurahan" class="form-label">Kelurahan</label>
                    <input required type="text" name="kelurahan" class="form-control " id="kelurahan">
                </div>

                <div class="mb-3">
                    <label for="kecamatan" class="form-label">Kecamatan</label>
                    <input required type="text" name="kecamatan" class="form-control " id="kecamatan">
                </div>

                <div class="mb-3">
                    <label for="kabkot" class="form-label">Kabupaten/Kota</label>
                    <input required type="text" name="kabkot" class="form-control " id="kabkot">
                </div>

                <div class="mb-3">
                    <label for="prov" class="form-label">Provinsi</label>
                    <input required type="text" name="prov" class="form-control " id="prov">
                </div>

                <button type="submit" class="btn btn-success btn-block">Simpan</button>
            </form>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/faskes_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
{% endblock %}

{% block title %} Detail Faskes {% endblock %}

{% block body %}
<div class="card m-3">
    <h3 class="card-header"> Data Fasilitas Kesehatan </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Kode Faskes: {{ data.kode }} <br>
            Tipe: {{ data.tipe }} <br>
            Nama Faskes: {{ data.nama }} <br>
            Status Kepemilikan: {{ data.statusmilik }} <br><br>
            Alamat <br>
            Jalan: {{ data.jalan }} <br>
            Kelurahan: {{ data.kelurahan }} <br>
            Kecamatan: {{ data.kecamatan }} <br>
            Kabupaten/Kota: {{ data.kabkot }} <br>
            Provinsi: {{ data.prov }} <br>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/faskes_read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
    </style>
{% endblock %}

{% block title %} List Faskes {% endblock %}

{% block body %}
<!-- <h1 class="m-3">List Reservasi RS</h1> -->

<p class="text--center" id="message" style="color: white;background-color: red;border-radius: 7px;">{{message}}</p>
<div class="card m-3">
    <h3 class="card-header"> List Faskes </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <table style="width:100%; border: 1px solid black" >
                <tr>
                    <th>Kode Faskes</th>
                    <th>Tipe</th>
                    <th>Nama Faskes</th>
                    <th>Action</th>
                </tr>
                {% for faskes in list_faskes %}
                <tr class="table-row">
                    <th>{{ faskes.kode }}</th>
                    <th>{{ faskes.tipe }}</th>
                    <th>{{ faskes.nama }}</th>
                    <th>
                        <a href="{% url 'trigger3:update_faskes' faskes.kode %}">Update</a><br>
                        <a href="{% url 'trigger3:delete_faskes' faskes.kode %}">Delete</a><br>
                        <a href="{% url 'trigger3:detail_faskes' faskes.kode %}">Detail</a>
                    </th>
                </tr>
                {% endfor %}
            </table>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/faskes_update.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
{% endblock %}

{% block title %} Update Faskes {% endblock %}

{% block body %}
<div class="card m-3">
    <h3 class="card-header"> Update Faskes </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="kode" class="form-label">Kode Faskes</label>
                    <input required readonly="readonly" type="text" name="kode" class="form-control " id="kode" value="{{ data.kode }}">
                </div>

                <div class="mb-3">
                    <label for="tipe" class="form-label">Tipe</label>
                    <input required type="text" name="tipe" class="form-control " id="tipe">
                </div>

                
                <div class="mb-3">
                    <label for="nama" class="form-label">Nama Faskes</label>
                    <input required type="text" name="nama" class="form-control " id="nama">
                </div>
                
                <div class="mb-3">
                    <label for="statusmilik" class="form-label">Status Kepemilikan</label>
                    <input required type="text" name="statusmilik" class="form-control " id="statusmilik">
                </div>

                <h3>Alamat</h3>

                <div class="mb-3">
                    <label for="jalan" class="form-label">Jalan</label>
                    <input required type="text" name="jalan" class="form-control " id="jalan">
                </div>

                <div class="mb-3">
                    <label for="kelurahan" class="form-label">Kelurahan</label>
                    <input required type="text" name="kelurahan" class="form-control " id="kelurahan">
                </div>

                <div class="mb-3">
                    <label for="kecamatan" class="form-label">Kecamatan</label>
                    <input required type="text" name="kecamatan" class="form-control " id="kecamatan">
                </div>

                <div class="mb-3">
                    <label for="kabkot" class="form-label">Kabupaten/Kota</label>
                    <input required type="text" name="kabkot" class="form-control " id="kabkot">
                </div>

                <div class="mb-3">
                    <label for="prov" class="form-label">Provinsi</label>
                    <input required type="text" name="prov" class="form-control " id="prov">
                </div>

                <button type="submit" class="btn btn-success btn-block">Simpan</button>
            </form>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/jadwal_faskes_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
{% endblock %}

{% block title %} Create Jadwal Faskes {% endblock %}

{% block body %}
<div class="card m-3">
    <h3 class="card-header"> Create Jadwal Faskes </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="kodefaskes" class="form-label">Faskes</label>
                    <select name="kodefaskes" id="kodefaskes" class="form-control">
                        <option value="" disabled selected>Select your option</option>
                        {% for data in list_kode %}
                        <option value="{{ data.kode }}">{{ data.kode }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="mb-3">
                    <label for="shift" class="form-label">Shift</label>
                    <input required type="text" name="shift" class="form-control " id="shift">
                </div>

                <div class="mb-3">
                    <label for="tanggal" class="form-label">Tanggal</label>
                    <input required type="text" name="tanggal" class="form-control " id="tanggal" placeholder="dd-mm-yyyy">
                </div>

                <button type="submit" class="btn btn-success btn-block">Simpan</button>
            </form>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/jadwal_faskes_read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
    </style>
{% endblock %}

{% block title %} List Jadwal Faskes {% endblock %}

{% block body %}
<!-- <h1 class="m-3">List Reservasi RS</h1> -->

<div class="card m-3">
    <h3 class="card-header"> List Jadwal Faskes </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <table style="width:100%; border: 1px solid black" >
                <tr>
                    <th>No.</th>
                    <th>Faskes</th>
                    <th>Shift</th>
                    <th>Tanggal</th>
                </tr>
                {% for jadwal in list_jadwal %}
                <tr class="table-row">
                    <th></th>
                    <th>{{ jadwal.kode_faskes }}</th>
                    <th>{{ jadwal.shift }}</th>
                    <th>{{ jadwal.tanggal }}</th>
                </tr>
                {% endfor %}
            </table>
        </li>
    </ul>
</div>

<script>
    var rows = document.getElementsByClassName('table-row');

    for (var i = 0, len = rows.length; i < len; i++) {
        rows[i].children[0].innerHTML = (i + 1) + '.';
    }
</script>
{% endblock %}

trigger3/templates/reservasi_rs_read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
    </style>
{% endblock %}

{% block title %} List Reservasi RS {% endblock %}

{% block body %}
<!-- <h1 class="m-3">List Reservasi RS</h1> -->

<p class="text--center" id="message" style="color: white;background-color: red;border-radius: 7px;">{{message}}</p>
<div class="card m-3">
    <h3 class="card-header"> List Reservasi RS </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <table style="width:100%; border: 1px solid black" >
                <tr>
                    <th class="table-head">No.</th>
                    <th class="table-head">NIK Pasien</th>
                    <th class="table-head">Tanggal Masuk</th>
                    <th class="table-head">Tanggal Keluar</th>
                    <th class="table-head">Rumah Sakit</th>
                    <th class="table-head">Ruangan</th>
                    <th class="table-head">Bed</th>
                    {% if request.session.role == 'SATGAS' %}
                    <th class="table-head">Action</th>
                    {% endif %}
                </tr>
                {% for reservasi in reservasi_rs %}
                <tr class="table-row">
                    <th class=""></th>
                    <th>{{ reservasi.kodepasien }}</th>
                    <th>{{ reservasi.tglmasuk }}</th>
                    <th>{{ reservasi.tglkeluar }}</th>
                    <th>{{ reservasi.koders }}</th>
                    <th>{{ reservasi.koderuangan }}</th>
                    <th>{{ reservasi.kodebed }}</th>
                    {% if request.session.role == 'SATGAS' %}
                    <th>
                        <a href="{% url 'trigger3:update_reservasi_rs' reservasi.kodepasien reservasi.tglmasuk %}">Update</a>
                        <a href="{% url 'trigger3:delete_reservasi_rs' reservasi.kodepasien reservasi.tglmasuk %}">Delete</a>
                    </th>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
        </li>
    </ul>
</div>

<script>
    var rows = document.getElementsByClassName('table-row');

    for (var i = 0, len = rows.length; i < len; i++) {
        rows[i].children[0].innerHTML = (i + 1) + '.';
    }
</script>
{% endblock %}

trigger3/templates/rs_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
{% endblock %}

{% block title %} Create Rumah Sakit {% endblock %}

{% block body %}
<p class="text--center" id="message" style="color: white;background-color: red;border-radius: 7px;">{{message}}</p>
<div class="card m-3">
    <h3 class="card-header"> Create Rumah Sakit </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="kodefaskes" class="form-label">Faskes</label>
                    <select name="kodefaskes" id="kodefaskes" class="form-control">
                        <option value="" disabled selected>Select your option</option>
                        {% for data in list_kode %}
                        <option value="{{ data.kode }}">{{ data.kode }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="mb-3">
                    <label for="isrujukan" class="form-label">Rujukan</label>
                    <input type="checkbox" name="isrujukan" id="isrujukan" value="1">
                </div>

                <button type="submit" class="btn btn-success btn-block">Simpan</button>
            </form>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/rs_read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
    </style>
{% endblock %}

{% block title %} List Rumah Sakit {% endblock %}

{% block body %}
<!-- <h1 class="m-3">List Reservasi RS</h1> -->

<div class="card m-3">
    <h3 class="card-header"> List Rumah Sakit </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <table style="width:100%; border: 1px solid black" >
                <tr>
                    <th>Kode</th>
                    <th>Rujukan?</th>
                    <th>Action</th>
                </tr>
                {% for rs in list_rs %}
                <tr class="table-row">
                    <th>{{ rs.kode_faskes }}</th>
                    {% if rs.isrujukan == '1' %}
                    <th><input type="checkbox" disabled checked></th>
                    {% else %}
                    <th><input type="checkbox" disabled></th>
                    {% endif %}
                    <th>
                        <a href="{% url 'trigger3:update_rs' rs.kode_faskes %}">Update</a><br>
                    </th>
                </tr>
                {% endfor %}
            </table>
        </li>
    </ul>
</div>
{% endblock %}

trigger3/templates/transaksi_rs_read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'home/../static/style.css' %}">
    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
        }
    </style>
{% endblock %}

{% block title %} List Transaksi RS {% endblock %}

{% block body %}
<!-- <h1 class="m-3">List Reservasi RS</h1> -->

<p class="text--center" id="message" style="color: white;background-color: red;border-radius: 7px;">{{message}}</p>
<div class="card m-3">
    <h3 class="card-header"> List Transaksi RS </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <table style="width:100%; border: 1px solid black" >
                <tr>
                    <th>ID Transaksi</th>
                    <th>Kode Pasien</th>
                    <th>Tanggal Pembayaran</th>
                    <th>Waktu Pembayaran</th>
                    <th>Tanggal Masuk</th>
                    <th>Total Biaya</th>
                    <th>Status Bayar</th>
                    <th>Action</th>
                </tr>
                {% for transaksi in list_transaksi %}
                <tr class="table-row">
                    <th>{{ transaksi.idtransaksi }}</th>
                    <th>{{ transaksi.kodepasien }}</th>
                    <th>{{ transaksi.tglpembayaran }}</th>
                    <th>{{ transaksi.waktupembayaran }}</th>
                    <th>{{ transaksi.tglmasuk }}</th>
                    <th>{{ transaksi.totalbiaya }}</th>
                    <th>{{ transaksi.statusbayar }}</th>
                    <th>
                        <a href="{% url 'trigger3:update_transaksi_rs' transaksi.idtransaksi %}">Update</a><br>
                        <a href="{% url 'trigger3:delete_transaksi_rs' transaksi.idtransaksi %}">Delete</a><br>
                    </th>
                </tr>
                {% endfor %}
            </table>
        </li>
    </ul>
</div>
{% endblock %}