home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

hotel/urls.py
from django.urls import path

from . import views

app_name = 'hotel'

urlpatterns = [
    path('hotel/', views.read_hotel, name='readhotel'),
    path('update/', views.update_hotel, name='updatehotel'),
    path('create/', views.create_hotel, name='createhotel'),
    path('delete/', views.delete_hotel, name='deletehotel'),
    path('rsv/', views.read_reservasi_hotel, name='readrsvhotel'),
    path('rsvupdate/', views.update_reservasi_hotel, name='updatersvhotel'),
    path('rsvcreate/', views.create_reservasi_hotel, name='creatersvhotel'),
    path('rsvdelete/', views.delete_reservasi_hotel, name='deletersvhotel'),
    path('trs/', views.read_transaksi_hotel, name='readtrshotel'),
    path('trsupdate/', views.update_transaksi_hotel, name='updatetrshotel'),
    # path('trscreate/', views.create_transaksi_hotel, name='createtrshotel'),
    path('trsdelete/', views.delete_transaksi_hotel, name='deletetrshotel'),
    path('bkg/', views.read_transaksi_booking, name='readtrsbooking'),
    # path('bkgcreate/', views.create_transaksi_booking, name='createtrsbooking'),
    path('bkgdelete/', views.delete_transaksi_booking, name='deletetrsbooking'),

]

siruco/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotel.urls')),
    path('', include('login.urls')),
    path('RumahSakit/',include('dokter.urls')),
    path('', include('trigger6.urls')),
    path('pasien/', include('pasien.urls')),
    path('', include('trigger3.urls')),
]

hotel/models.py
from django.db import models

# Create your models here.

hotel/views.py
from django.db import connection
from django.shortcuts import redirect, render

# Create your views here.

# def create_hotel(request):
#     if request.session["user_role"] == "Admin Sistem":
#         try:
#             KodeHotel = request.POST["KodeHotel"]

def create_hotel(request):
    if request.session["role"] == "ADMIN_SISTEM":
        context = {}
        if request.method == 'POST':
            try:
                KodeHotel = request.POST["KodeHotel"]
                JenisBed = request.POST["JenisBed"]
                Tipe = request.POST["Tipe"]
                Harga = request.POST["Harga"]
                # mencari max no_urut
                KodeRoom = "RM"
                no = 1
                with connection.cursor() as c:
                    # mengambil nomor urut terbesar terakhir
                    c.execute(
                        f"select KodeRoom from hotel_room where KodeHotel = '{KodeHotel}'")
                    row = c.fetchall()
                    rownew = str(row[-1])
                    x = int(rownew[4:7])
                    # jika table pelanggan sudah ada isinya
                    if rownew != None:
                        # no = str(int(row[0]) + 1)
                        no = x + 1
                sno = str(no)
                zno = sno
                if len(sno) < 3:
                    zno = sno.zfill(3)
                KodeRoom += zno

                # insert data
                with connection.cursor() as c:
                    command = f"INSERT INTO hotel_room VALUES"
                    command += f"('{KodeHotel}', '{KodeRoom}', '{JenisBed}', '{Tipe}', '{Harga}')"
                    # command = "INSERT INTO hotel_room VALUES "
                    # command += str(KodeHotel, KodeRoom, JenisBed,
                    #                 Tipe, str(Harga))
                    c.execute(command)
            except Exception as e:
                print(e)
                context["error"] = "Data yang Anda masukkan tidak valid mohon cek kembali"
                # mengambil semua kode
                # with connection.cursor() as c:
                #     c.execute("select * from item")
                #     context["daftar_kode"] = c.fetchall()
                # # mengambil semua email
                # with connection.cursor() as c:
                #     c.execute("select email from pelanggan")
                #     context["daftar_email"] = c.fetchall()
                return render(request, 'hotel/createhotel.html', context)
            return redirect('hotel:readhotel')
        else:
            data = []
            # mengambil semua kode
            with connection.cursor() as c:
                c.execute("select * from Hotel")
                context["daftar_Hotel"] = c.fetchall()
            # mengambil semua email
            with connection.cursor() as c:
                c.execute("select Kode from Hotel")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data.append((x[0]))
                context["data"] = data
            return render(request, 'hotel/createhotel.html', context)
    else:
        return render(request, 'hotel/gagal.html')

def read_hotel(request):
    if request.session["role"] in ["SATGAS", "PENGGUNA_PUBLIK", "ADMIN_SISTEM"]:
        data = []
        context = {}
        # mengambil semua daftar laundry
        with connection.cursor() as c:
            # if request.session["user_role"] == "pelanggan":
            #     email = request.session["user_email"]
            #     c.execute(f"select * from daftar_laundry where email = '{email}'")
            # else:
            #     c.execute("select * from daftar_laundry")
            c.execute("select * from hotel_room")
            dataSQL = c.fetchall()

            # convert date object to str (date object ada di index ke-1)
            for x in dataSQL:
                data.append((x[0], x[1], x[2], x[3], str(x[4])))
            context["data"] = data
        return render(request, 'hotel/readhotel.html', context)
    else:
        return render(request, 'hotel/gagal.html')

def delete_hotel(request):
    if request.session["role"] == "ADMIN_SISTEM":
        if request.method == "POST":
            with connection.cursor() as c:
                KodeHotel = request.POST["KodeHotel"]
                KodeRoom = request.POST["KodeRoom"]
                command = f"delete from hotel_room where KodeHotel = '{KodeHotel}' and "
                command += f"KodeRoom = '{KodeRoom}'"
                try:
                    c.execute(command)
                    print("success")
                except Exception as e:
                    print(e)
                return redirect('hotel:readhotel')
    else:
        return render(request, 'hotel/gagal.html')

def update_hotel(request):
    if request.session["role"] == "ADMIN_SISTEM":
        context = {}
        if request.method == "GET":
            # jika data ini ada di parameter get
            try:
                context["KodeHotel"] = request.GET["KodeHotel"]
                context["KodeRoom"] = request.GET["KodeRoom"]
                context["JenisBed"] = request.GET["JenisBed"]
                context["Tipe"] = request.GET["Tipe"]
                context["Harga"] = request.GET["Harga"]
            # jika tidak ada
            except:
                return redirect('hotel:readhotel')
            # mengambil semua kode item
            # with connection.cursor() as c:
            #     c.execute("select * from item")
            #     context["daftar_kode"] = c.fetchall()
            return render(request, 'hotel/updatehotel.html', context)
        if request.method == 'POST':
            # melakukan update
            with connection.cursor() as c:
                KodeHotel = request.POST["KodeHotel"]
                KodeRoom = request.POST["KodeRoom"]
                JenisBed = request.POST["JenisBed"]
                Tipe = request.POST["Tipe"]
                Harga = request.POST["Harga"]
                command = f"update hotel_room set "
                command += f"JenisBed = '{JenisBed}', Tipe = '{Tipe}', Harga = '{Harga}' "
                command += f"where KodeHotel = '{KodeHotel}' and KodeRoom = '{KodeRoom}' "
                # jika update berhasil
                try:
                    c.execute(command)
                    print("success")
                # jika gagal
                except Exception as e:
                    print(e)
            return redirect('hotel:readhotel')
    else:
        return render(request, 'hotel/gagal.html')

def create_reservasi_hotel(request):
    if request.session["role"] in ["SATGAS", "PENGGUNA_PUBLIK"]:
        context = {}
        if request.method == 'POST':
            try:
                KodePasien = request.POST["KodePasien"]
                TglMasuk = request.POST["TglMasuk"]
                TglKeluar = request.POST["TglKeluar"]
                KodeHotel = request.POST["KodeHotel"]
                KodeRoom = request.POST["KodeRoom"]

                # insert data
                with connection.cursor() as c:
                    command = f"INSERT INTO reservasi_hotel VALUES"
                    command += f"('{KodePasien}', '{TglMasuk}', '{TglKeluar}', '{KodeHotel}', '{KodeRoom}')"
                    c.execute(command)
            except Exception as e:
                print(e)
                context["error"] = "Data yang Anda masukkan tidak valid mohon cek kembali"
                # mengambil semua kode
                # with connection.cursor() as c:
                #     c.execute("select * from item")
                #     context["daftar_kode"] = c.fetchall()
                # # mengambil semua email
                # with connection.cursor() as c:
                #     c.execute("select email from pelanggan")
                #     context["daftar_email"] = c.fetchall()
                return render(request, 'hotel/creatersvhotel.html', context)
            return redirect('hotel:readrsvhotel')
        else:
            data_nik = []
            data_hotel = []
            data_room = []
            # mengambil semua email
            with connection.cursor() as c:
                c.execute("select NIK from PASIEN")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data_nik.append((x[0]))
                context["data_nik"] = data_nik

            with connection.cursor() as c:
                c.execute("select Kode from HOTEL")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data_hotel.append((x[0]))
                context["data_hotel"] = data_hotel

            with connection.cursor() as c:
                c.execute("select KodeRoom from HOTEL_ROOM")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data_room.append((x[0]))
                context["data_room"] = data_room
            
            return render(request, 'hotel/creatersvhotel.html', context)
    else:
        return render(request, 'hotel/gagal.html')

def read_reservasi_hotel(request):
    if request.session["role"] in ["SATGAS", "PENGGUNA_PUBLIK"]:
        data = []
        context = {}
        # mengambil semua daftar laundry
        with connection.cursor() as c:
            # if request.session["user_role"] == "pelanggan":
            #     email = request.session["user_email"]
            #     c.execute(f"select * from daftar_laundry where email = '{email}'")
            # else:
            #     c.execute("select * from daftar_laundry")
            c.execute("select * from reservasi_hotel")
            dataSQL = c.fetchall()

            # convert date object to str (date object ada di index ke-1)
            for x in dataSQL:
                data.append((x[0], str(x[1]), str(x[2]), x[3], x[4]))
            context["data"] = data
        return render(request, 'hotel/readrsvhotel.html', context)
    else:

hotel/templates/hotel/createhotelc.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock %}

{% block title %}Buat Ruangan Hotel{% endblock %}

{% block body %}
<h3 class="mt-5 text-center">Buat Ruangan Hotel</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'hotel:createhotel' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <select name="email" id="email" class="form-control" required>
        <option selected disabled>Pilih...</option>
        {% for d in data  %}
        <option value="{{ d.0 }}">{{ d.0 }}</option>
        {% endfor %}
      </select>
      <small class="form-text text-danger">{{ error }}</small>
    </div>
    <div class="form-group">
      <label for="tanggal">Tanggal Transaksi</label>
      <select name="tanggal" id="tanggal" class="form-control" required>
        <option selected disabled>Pilih...</option>
        <div id="select-tanggal">
          {% for d in data  %}
          <option class="option-tanggal d-none" data-email="{{ d.0 }}" value="{{ d.1 }}">{{ d.1 }}</option>
          {% endfor %}
          </div>
      </select>
    </div>
    <div class="form-group">
      <label for="jumlah_item">Jumlah Item.</label>
      <input
        required
        type="number"
        class="form-control"
        id="jumlah_item"
        name="jumlah_item"
      />
    </div>
    
    <div class="form-group">
      <label for="kode_item">Kode Item</label>
      <select name="kode_item" id="kode_item" class="form-control" required>
        <option selected disabled>Pilih...</option>
        {% for k in daftar_kode %}
        <option value="{{ k.0 }}">{{ k.0 }} : {{ k.1 }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">
        Buat Daftar Laundry
      </button>
    </div>
  </form>
</div>

<script>
  $('select#email').change(() => {
    $('.option-tanggal').addClass('d-none')
    $('.option-tanggal').each((i, el) => {
      if ($(el).data("email") == $('select#email').val()) {
        $(el).removeClass('d-none')
      }
    })
  })
</script>

{% endblock %}

hotel/templates/hotel/gagal.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <style>
    body {
        counter-reset: Serial;           /* Set the Serial counter to 0 */
    }

    table {
        border-collapse: separate;
    }

    tr td:first-child:before {
        counter-increment: Serial;      /* Increment the Serial counter */
        content: counter(Serial); /* Display the counter */
    }
  </style>
{% endblock %}

{% block title %}Hotel{% endblock %}

{% block body %}
<h3 class="text-center mt-5">Anda Tidak Dapat Akses Bagian Ini</h3>
{% endblock %}

hotel/templates/hotel/readhotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <style>
    body {
        counter-reset: Serial;           /* Set the Serial counter to 0 */
    }

    table {
        border-collapse: separate;
    }

    tr td:first-child:before {
        counter-increment: Serial;      /* Increment the Serial counter */
        content: counter(Serial); /* Display the counter */
    }
  </style>
{% endblock %}

{% block title %}Hotel{% endblock %}

{% block body %}
<h3 class="text-center mt-5">List Ruangan Hotel</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Kode Hotel</th>
        <th scope="col">Kode Ruangan</th>
        <th scope="col">Jenis Bed</th>
        <th scope="col">Tipe</th>
        <th scope="col">Harga</th>
        {% if request.session.role == 'ADMIN_SISTEM' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for hotel in data %}  
      <tr>
        <td></td>
        <td>{{ hotel.0 }}</td>
        <td>{{ hotel.1 }}</td>
        <td>{{ hotel.2 }}</td>
        <td>{{ hotel.3 }}</td>
        <td>{{ hotel.4 }}</td>
        {% if request.session.role == 'ADMIN_SISTEM' %}
        <td>
          <div class="d-flex">
            <form action="{% url 'hotel:updatehotel' %}" method="get">
                <input type="text" name="KodeHotel" value="{{ hotel.0 }}" hidden>
                <input type="text" name="KodeRoom" value="{{ hotel.1 }}" hidden>
                <input type="text" name="JenisBed" value="{{ hotel.2 }}" hidden>
                <input type="text" name="Tipe" value="{{ hotel.3 }}" hidden>
                <input type="number" name="Harga" value="{{ hotel.4 }}" hidden>
                <button class="btn btn-primary mr-2">Update</button>
            </form>
            <form action="{% url 'hotel:deletehotel' %}" method="post">
                {% csrf_token %}
                <input type="text" name="KodeHotel" value="{{ hotel.0 }}" hidden>
                <input type="text" name="KodeRoom" value="{{ hotel.1 }}" hidden>
                <button class="btn btn-delete btn-danger">Delete</button>
            </form>
          </div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

hotel/templates/hotel/readrsvhotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <style>
    body {
        counter-reset: Serial;           /* Set the Serial counter to 0 */
    }

    table {
        border-collapse: separate;
    }

    tr td:first-child:before {
        counter-increment: Serial;      /* Increment the Serial counter */
        content: counter(Serial); /* Display the counter */
    }
  </style>
{% endblock %}

{% block title %}Reservasi Hotel{% endblock %}

{% block body %}
<h3 class="text-center mt-5">List Reservasi Hotel</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">NIK Pasien</th>
        <th scope="col">Tanggal Masuk</th>
        <th scope="col">Tanggal Keluar</th>
        <th scope="col">Kode Hotel</th>
        <th scope="col">Ruangan</th>
        {% if request.session.role == 'SATGAS' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for rsv in data %}  
      <tr>
        <td></td>
        <td>{{ rsv.0 }}</td>
        <td>{{ rsv.1 }}</td>
        <td>{{ rsv.2 }}</td>
        <td>{{ rsv.3 }}</td>
        <td>{{ rsv.4 }}</td>
        {% if request.session.role == 'SATGAS' %}
        <td>
          <div class="d-flex">
            <form action="{% url 'hotel:updatersvhotel' %}" method="get">
                <input type="text" name="KodePasien" value="{{ rsv.0 }}" hidden>
                <input type="text" name="TglMasuk" value="{{ rsv.1 }}" hidden>
                <input type="text" name="TglKeluar" value="{{ rsv.2 }}" hidden>
                <input type="text" name="KodeHotel" value="{{ rsv.3 }}" hidden>
                <input type="text" name="KodeRoom" value="{{ rsv.4 }}" hidden>
                <button class="btn btn-primary mr-2">Update</button>
            </form>
            <form action="{% url 'hotel:deletersvhotel' %}" method="post">
                {% csrf_token %}
                <input type="text" name="KodePasien" value="{{ rsv.0 }}" hidden>
                <input type="text" name="TglMasuk" value="{{ rsv.1 }}" hidden>
                <button class="btn btn-delete btn-danger">Delete</button>
            </form>
          </div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

hotel/templates/hotel/readtrsbooking.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <style>
    body {
        counter-reset: Serial;           /* Set the Serial counter to 0 */
    }

    table {
        border-collapse: separate;
    }

    tr td:first-child:before {
        counter-increment: Serial;      /* Increment the Serial counter */
        content: counter(Serial); /* Display the counter */
    }
  </style>
{% endblock %}

{% block title %}Transaksi Booking{% endblock %}

{% block body %}
<h3 class="text-center mt-5">List Transaksi Booking</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Id Transaksi</th>
        <th scope="col">Total Bayar</th>
        <th scope="col">Kode Pasien</th>
        <th scope="col">Tanggal masuk</th>
        {% if request.session.role == 'SATGAS' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for bkg in data %}  
      <tr>
        <td></td>
        <td>{{ bkg.0 }}</td>
        <td>{{ bkg.1 }}</td>
        <td>{{ bkg.2 }}</td>
        <td>{{ bkg.3 }}</td>
        {% if request.session.role == 'SATGAS' %}
        <td>
          <div class="d-flex">
            <form action="{% url 'hotel:deletetrsbooking' %}" method="post">
                {% csrf_token %}
                <input type="text" name="IdTransaksiBooking" value="{{ bkg.0 }}" hidden>
                <button class="btn btn-delete btn-danger">Delete</button>
            </form>
          </div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

hotel/templates/hotel/readtrshotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <style>
    body {
        counter-reset: Serial;           /* Set the Serial counter to 0 */
    }

    table {
        border-collapse: separate;
    }

    tr td:first-child:before {
        counter-increment: Serial;      /* Increment the Serial counter */
        content: counter(Serial); /* Display the counter */
    }
  </style>
{% endblock %}

{% block title %}Transaksi Hotel{% endblock %}

{% block body %}
<h3 class="text-center mt-5">List Transaksi Hotel</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Id Transaksi</th>
        <th scope="col">NIK Pasien</th>
        <th scope="col">Tanggal Pembayaran</th>
        <th scope="col">Waktu Pembayaran</th>
        <th scope="col">Total Bayar</th>
        <th scope="col">Status</th>
        {% if request.session.role == 'SATGAS' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for trs in data %}  
      <tr>
        <td></td>
        <td>{{ trs.0 }}</td>
        <td>{{ trs.1 }}</td>
        <td>{{ trs.2 }}</td>
        <td>{{ trs.3 }}</td>
        <td>{{ trs.4 }}</td>
        <td>{{ trs.5 }}</td>
        {% if request.session.role == 'SATGAS' %}
        <td>
          <div class="d-flex">
            <form action="{% url 'hotel:updatetrshotel' %}" method="get">
                <input type="text" name="IdTransaksi" value="{{ trs.0 }}" hidden>
                <input type="text" name="KodePasien" value="{{ trs.1 }}" hidden>
                <input type="date" name="TanggalPembayaran" value="{{ trs.2 }}" hidden>
                <input type="timestamp" name="WaktuPembayaran" value="{{ trs.3 }}" hidden>
                <input type="number" name="TotalBayar" value="{{ trs.4 }}" hidden>
                <input type="text" name="StatusBayar" value="{{ trs.5 }}" hidden>
                <button class="btn btn-primary mr-2">Update</button>
            </form>
            <form action="{% url 'hotel:deletetrshotel' %}" method="post">
                {% csrf_token %}
                <input type="text" name="IdTransaksi" value="{{ trs.0 }}" hidden>
                <input type="text" name="KodePasien" value="{{ trs.1 }}" hidden>
                <button class="btn btn-delete btn-danger">Delete</button>
            </form>
          </div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

hotel/templates/hotel/updatehotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock %}

{% block title %}Hotel{% endblock %}

{% block body %}
<h3 class="mt-5 text-center">Update Hotel</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'hotel:updatehotel' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="KodeHotel">Kode Hotel</label>
      <input
        readonly
        required
        value="{{ KodeHotel }}"
        type="text"
        class="form-control"
        id="KodeHotel"
        name="KodeHotel"
      />
    </div>
    <div class="form-group">
      <label for="KodeRoom">Kode Room</label>
      <input
        readonly
        required
        value="{{ KodeRoom }}"
        type="text"
        class="form-control"
        id="KodeRoom"
        name="KodeRoom"
      />
    </div>
    <div class="form-group">
      <label for="JenisBed">Jenis Bed</label>
      <input
        required
        value="{{ JenisBed }}"
        type="text"
        class="form-control"
        id="JenisBed"
        name="JenisBed"
      />
    </div>
    <div class="form-group">
      <label for="Tipe">Tipe</label>
      <input
        required
        value="{{ Tipe }}"
        type="text"
        class="form-control"
        id="Tipe"
        name="Tipe"
      />
    </div>
    <div class="form-group">
      <label for="Harga">Harga</label>
      <input
        required
        value="{{ Harga }}"
        type="number"
        class="form-control"
        id="Harga"
        name="Harga"
      />
    </div>
    {% comment %} <div class="form-group">
      <label for="kode_item">Kode Item</label>
      <select name="kode_item" id="kode_item" class="form-control" required>
        {% for k in daftar_kode %}
        <option {% if k.0 == kode %}selected{% endif %} value="{{ k.0 }}">{{ k.0 }} : {{ k.1 }}</option>
        {% endfor %}
      </select>
    </div> {% endcomment %}
  
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">Update</button>
    </div>
  </form>
</div>
{% endblock %}

hotel/templates/hotel/updatersvhotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock %}

{% block title %}Reservasi Hotel{% endblock %}

{% block body %}
<h3 class="mt-5 text-center">Update Reservasi Hotel</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'hotel:updatersvhotel' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="KodePasien">Kode Pasien</label>
      <input
        readonly
        required
        value="{{ KodePasien }}"
        type="text"
        class="form-control"
        id="KodePasien"
        name="KodePasien"
      />
    </div>
    <div class="form-group">
      <label for="TglMasuk">Tgl Masuk</label>
      <input
        readonly
        required
        value="{{ TglMasuk }}"
        type="date"
        class="form-control"
        id="TglMasuk"
        name="TglMasuk"
      />
    </div>
    <div class="form-group">
      <label for="TglKeluar">Tgl Keluar</label>
      <input
        required
        value="{{ TglKeluar }}"
        type="date"
        class="form-control"
        id="TglKeluar"
        name="TglKeluar"
      />
    </div>
    <div class="form-group">
      <label for="KodeHotel">Kode Hotel</label>
      <input
        readonly
        required
        value="{{ KodeHotel }}"
        type="text"
        class="form-control"
        id="KodeHotel"
        name="KodeHotel"
      />
    </div>
    <div class="form-group">
      <label for="KodeRoom">Kode Room</label>
      <input
        readonly
        required
        value="{{ KodeRoom }}"
        type="text"
        class="form-control"
        id="KodeRoom"
        name="KodeRoom"
      />
    </div>
    {% comment %} <div class="form-group">
      <label for="kode_item">Kode Item</label>
      <select name="kode_item" id="kode_item" class="form-control" required>
        {% for k in daftar_kode %}
        <option {% if k.0 == kode %}selected{% endif %} value="{{ k.0 }}">{{ k.0 }} : {{ k.1 }}</option>
        {% endfor %}
      </select>
    </div> {% endcomment %}
  
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">Update</button>
    </div>
  </form>
</div>
{% endblock %}