dokter/urls.py
from django.urls import path
from . import views

app_name = 'dokter'

urlpatterns = [
    path('createJadwalDokter/', views.jadwalDokter, name = 'createJadwalDokter'),
    path('jadwalDokter/',views.jadwalDokterList,name = 'jadwalDokter' ),
    path('createAppointment/',views.createAppointment,name = 'createAppointment'),
    path('appointment/',views.appointment,name = 'Appointment'),
    path('createRuanganRS/',views.createRuanganRS,name = 'createRuanganRS'),
    path('RuanganRS/',views.RuanganRS,name = 'RuanganRS'),
    path('createBed/',views.createBed,name = 'createBed'),
    path('bed/',views.bed,name = 'bed'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

hotel/urls.py
from django.urls import path

from . import views

app_name = 'hotel'

urlpatterns = [
    path('hotel/', views.read_hotel, name='readhotel'),
    path('update/', views.update_hotel, name='updatehotel'),
    path('create/', views.create_hotel, name='createhotel'),
    path('delete/', views.delete_hotel, name='deletehotel'),
    path('rsv/', views.read_reservasi_hotel, name='readrsvhotel'),
    path('rsvupdate/', views.update_reservasi_hotel, name='updatersvhotel'),
    path('rsvcreate/', views.create_reservasi_hotel, name='creatersvhotel'),
    path('rsvdelete/', views.delete_reservasi_hotel, name='deletersvhotel'),
    path('trs/', views.read_transaksi_hotel, name='readtrshotel'),
    path('trsupdate/', views.update_transaksi_hotel, name='updatetrshotel'),
    # path('trscreate/', views.create_transaksi_hotel, name='createtrshotel'),
    path('trsdelete/', views.delete_transaksi_hotel, name='deletetrshotel'),
    path('bkg/', views.read_transaksi_booking, name='readtrsbooking'),
    # path('bkgcreate/', views.create_transaksi_booking, name='createtrsbooking'),
    path('bkgdelete/', views.delete_transaksi_booking, name='deletetrsbooking'),

]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout')
]

pasien/urls.py
from django.urls import path
from . import views

app_name = 'pasien'

urlpatterns = [
    path('', views.listPasien, name = 'listPasien'),
    path('daftar/', views.daftarPasien, name = 'daftarPasien'),
    path('detail/<str:nik_pasien>', views.detailPasien, name = 'detailPasien'),
    path('delete/<str:nik_pasien>', views.deletePasien, name = 'deletePasien'),
    path('update/<str:nik_pasien>', views.updatePasien, name = 'updatePasien'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotel.urls')),
    path('', include('login.urls')),
    path('RumahSakit/',include('dokter.urls')),
    path('', include('trigger6.urls')),
    path('pasien/', include('pasien.urls')),
    path('', include('trigger3.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import redirect, render
from django.db import connection
from collections import namedtuple
from django.contrib import messages

from login.views import namedtuplefetchall, dictfetchone

def index(request):
    try:
        if request.session['role'] == 'ADMIN_SISTEM':
            return dashboardAdmin(request)
        elif request.session['role'] == 'PENGGUNA_PUBLIK':
            return dashboardPublik(request)
        elif request.session['role'] == 'SATGAS':
            return dashboardSatgas(request)
        elif request.session['role'] == 'DOKTER':
            return dashboardDokter(request)
    except:
        return render(request, 'index.html')

def dashboardAdmin(request):
    c = connection.cursor()
    c.execute('SELECT * FROM ADMIN WHERE username=%s', [request.session['username']])
    return render(request, 'dashboard_admin.html', {'data': dictfetchone(c)})

def dashboardPublik(request):
    c = connection.cursor()
    c.execute('SELECT * FROM PENGGUNA_PUBLIK WHERE username=%s', [request.session['username']])
    return render(request, 'dashboard_publik.html', {'data': dictfetchone(c)})

def dashboardSatgas(request):
    c = connection.cursor()
    c.execute('SELECT * FROM ADMIN_SATGAS WHERE username=%s', [request.session['username']])
    return render(request, 'dashboard_satgas.html', {'data': dictfetchone(c)})

def dashboardDokter(request):
    c = connection.cursor()
    c.execute('SELECT * FROM DOKTER WHERE username=%s', [request.session['username']])
    return render(request, 'dashboard_dokter.html', {'data': dictfetchone(c)})

home/templates/dashboard_admin.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Dashboard Admin Sistem {% endblock %}

{% block body %}
<h1 class="m-3">This is Dashboard for Admin Sistem</h1>

<div class="card m-3">
    <h3 class="card-header"> Profile </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"> Username: {{ data.username }}</li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header">Hotel</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href=""> Buat Hotel </a></li>
        <li class="list-group-item"><a href=""> List Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:createhotel' %}"> Buat Ruangan Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readhotel' %}"> List Ruangan Hotel </a></li>
        <li class="list-group-item"><a href=""> Buat Paket Makan </a></li>
        <li class="list-group-item"><a href=""> List Paket Makan </a></li>
    </ul>
</div>

{% endblock %}

home/templates/dashboard_dokter.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Dashboard Dokter {% endblock %}

{% block body %}
<h1 class="m-3">This is Dashboard for Dokter</h1>
<!--{% if messages %}-->
<!--  <ul class="messages">-->
<!--    {% for message in messages %}-->
<!--      <li class="{{ message.tags }}">{{ message }}</li>-->
<!--    {% endfor %}-->
<!--  </ul>-->
<!--{% endif %}-->
<div class="card m-3">
    <h3 class="card-header"> Profile </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"> Username: {{ data.username }}</li>
        <li class="list-group-item"> No STR: {{ data.nostr }}</li>
        <li class="list-group-item"> Nama: {{ data.nama }}</li>
        <li class="list-group-item"> Nomor HP: {{ data.nohp }}</li>
        <li class="list-group-item"> Gelar Depan: {{ data.gelardepan }}</li>
        <li class="list-group-item"> Gelar Belakang: {{ data.gelarbelakang }}</li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header">Pasien</h3>
    <ul class="list-group list-group-flush">

        <li class="list-group-item"><a href="{% url 'dokter:Appointment' %}"> List Appointment </a></li>
        <li class="list-group-item"><a href="{% url 'trigger6:createHasilTesPasien' %}"> Buat Hasil Tes Pasien </a></li>
        <li class="list-group-item"><a href="{% url 'trigger6:listHasilTesPasien' %}"> List Hasil Tes Pasien </a></li>

    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header">Rumah Sakit</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'dokter:createJadwalDokter' %}"> Buat Jadwal Dokter </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:jadwalDokter' %}"> List Jadwal Dokter </a></li>
    </ul>
</div>

{% endblock %}

home/templates/dashboard_publik.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Dashboard Pengguna Publik {% endblock %}

{% block body %}
<h1 class="m-3">This is Dashboard for Pengguna Publik</h1>

<div class="card m-3">
    <h3 class="card-header"> Profile </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"> Username: {{ data.username }}</li>
        <li class="list-group-item"> NIK: {{ data.nik }}</li>
        <li class="list-group-item"> Nama: {{ data.nama }}</li>
        <li class="list-group-item"> Status: {{ data.status }}</li>
        <li class="list-group-item"> Peran: {{ data.peran }}</li>
        <li class="list-group-item"> Nomor HP: {{ data.nohp }}</li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header">Pasien</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'pasien:daftarPasien' %}"> Pendaftaran Pasien </a></li>
        <li class="list-group-item"><a href="{% url 'pasien:listPasien' %}"> List Pasien </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:createAppointment' %}"> Buat Appointment </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:Appointment' %}"> List Appointment </a></li>
        <li class="list-group-item"><a href="{% url 'trigger6:listHasilTesPasien' %}"> List Hasil Tes Pasien </a></li>

    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Rumah Sakit </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href=""> List Jadwal Dokter </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:list_reservasi_rs' %}"> List Reservasi RS </a></li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Hotel </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href=""> List Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readhotel' %}"> List Ruangan Hotel </a></li>
        <li class="list-group-item"><a href=""> List Paket Makan </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:creatersvhotel' %}"> Buat Reservasi Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readrsvhotel' %}"> List Reservasi Hotel </a></li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Transaksi </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'trigger6:listTransaksiRS' %}"> Bayar Transaksi RS </a></li>
        <li class="list-group-item"><a href="{% url 'trigger6:listTransaksiHotel' %}"> Bayar Transaksi Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readtrshotel' %}"> List Transaksi Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readtrsbooking' %}"> List Transaksi Booking Hotel </a></li>
        <li class="list-group-item"><a href=""> Buat Transaksi Makan dan Daftar Pesan </a></li>
        <li class="list-group-item"><a href=""> List Transaksi Makan dan Daftar Pesan </a></li>
    </ul>
</div>

{% endblock %}

home/templates/dashboard_satgas.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Dashboard Satgas {% endblock %}

{% block body %}
<h1 class="m-3">This is Dashboard for Satgas</h1>

<div class="card m-3">
    <h3 class="card-header"> Profile </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"> Username: {{ data.username }}</li>
        <li class="list-group-item"> ID Faskes: {{ data.idfaskes }}</li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Pasien </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'dokter:createAppointment' %}"> Buat Appointment </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:Appointment' %}"> List Appointment </a></li>
        <li class="list-group-item"><a href=""> List Hasil Tes Pasien </a></li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Faskes </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'trigger3:create_faskes' %}"> Buat Faskes </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:read_faskes' %}"> List Faskes </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:create_jadwal_faskes' %}"> Buat Jadwal Faskes </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:read_jadwal_faskes' %}"> List Jadwal Faskes </a></li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Rumah Sakit </h3>
    <ul class="list-group list-group-flush">

        <li class="list-group-item"><a href="{% url 'trigger3:create_rs' %}"> Buat RS </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:read_rs' %}"> List RS </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:jadwalDokter' %}"> List Jadwal Dokter </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:createRuanganRS' %}"> Buat Ruangan RS </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:RuanganRS' %}"> List Ruangan RS </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:createBed' %}"> Buat Bed RS </a></li>
        <li class="list-group-item"><a href="{% url 'dokter:bed' %}"> List Bed RS </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:create_reservasi_rs' %}"> Buat Reservasi RS </a></li>
        <li class="list-group-item"><a href="{% url 'trigger3:list_reservasi_rs' %}"> List Reservasi RS </a></li>

    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Hotel </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href=""> List Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readhotel' %}"> List Ruangan Hotel </a></li>
        <li class="list-group-item"><a href=""> List Paket Makan </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:creatersvhotel' %}"> Buat Reservasi Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readrsvhotel' %}"> List Reservasi Hotel </a></li>
    </ul>
</div>

<div class="card m-3">
    <h3 class="card-header"> Transaksi </h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'trigger3:read_transaksi_rs' %}"> List Transaksi RS </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readtrshotel' %}"> List Transaksi Hotel </a></li>
        <li class="list-group-item"><a href="{% url 'hotel:readtrsbooking' %}"> List Transaksi Booking Hotel </a></li>
        <li class="list-group-item"><a href=""> Buat Transaksi Makan dan Daftar Pesan </a></li>
        <li class="list-group-item"><a href=""> List Transaksi Makan dan Daftar Pesan </a></li>
    </ul>
</div>

{% endblock %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} SIRUCO {% endblock %}

{% block body %}
<h1 class="m-3">Selamat Datang di SIRUCO</h1>

<div class="card m-3">
    <h3 class="card-header"><a href="{% url 'login:login' %}"> Login </a></h3>
</div>

<div class="card m-3">
    <h3 class="card-header"><a href="{% url 'login:register' %}"> Register </a></h3>
</div>

{% endblock %}