home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotel.urls')),
    path('', include('login.urls')),
    path('RumahSakit/',include('dokter.urls')),
    path('', include('trigger6.urls')),
    path('pasien/', include('pasien.urls')),
    path('', include('trigger3.urls')),
]

trigger6/urls.py
from django.urls import path
from . import views

app_name = 'trigger6'

urlpatterns = [
    path('transaksi/rs/', views.listTransaksiRS, name = 'listTransaksiRS'),
    path('transaksi/rs/<str:id_transaksi>', views.detailTransaksiRS, name = 'detailTransaksiRS'),
    path('transaksi/rs/update/<str:id_transaksi>', views.updateTransaksiRS, name = 'updateTransaksiRS'),
    
    path('transaksi/hotel/', views.listTransaksiHotel, name = 'listTransaksiHotel'),
    path('transaksi/hotel/<str:id_transaksi>', views.detailTransaksiHotel, name = 'detailTransaksiHotel'),
    path('transaksi/hotel/update/<str:id_transaksi>', views.updateTransaksiHotel, name = 'updateTransaksiHotel'),
    
    path('hasil-tes/', views.listHasilTesPasien, name = 'listHasilTesPasien'),
    path('hasil-tes/create/', views.createHasilTesPasien, name = 'createHasilTesPasien'),
]

trigger6/models.py
from django.db import models

# Create your models here.

trigger6/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from trigger6.utils import *

# 19. Membayar Transaksi RS [READ]
def listTransaksiRS(request):
    context = {
        'listTransaksi': getListTransaksiRS(request.session['username'])
    }
    return render(request, 'transaksi_rs.html', context)

# 19. Membayar Transaksi RS [READ]
def detailTransaksiRS(request, id_transaksi):
    context = {
        'data': getDetailTransaksiRS(id_transaksi)
    }
    return render(request, 'detail_transaksi_rs.html', context)

# 19. Membayar Transaksi RS [UPDATE]
def updateTransaksiRS(request, id_transaksi):
    updateStatusTransaksiRS(id_transaksi)
    return redirect('/transaksi/rs')

# 20. Membayar Transaksi Hotel [READ]
def listTransaksiHotel(request):
    context = {
        'listTransaksi': getListTransaksiHotel(request.session['username'])
    }
    return render(request, 'transaksi_hotel.html', context)

# 20. Membayar Transaksi Hotel [READ]
def detailTransaksiHotel(request, id_transaksi):
    context = {
        'data': getDetailTransaksiHotel(id_transaksi),
        'booking': getDetailTransaksiBooking(id_transaksi),
        'listMakan': getDetailTransaksiMakan(id_transaksi)
    }
    return render(request, 'detail_transaksi_hotel.html', context)

# 20. Membayar Transaksi Hotel [UPDATE]
def updateTransaksiHotel(request, id_transaksi):
    updateStatusTransaksiHotel(id_transaksi)
    return redirect('/transaksi/hotel')

# 21. Hasil Tes Pasien [READ]
def listHasilTesPasien(request):
    context = {
        'listHasil': getListHasilTesPasien(request.session['username'], request.session['role'])
    }
    return render(request, 'hasil_tes.html', context)

# 21. Hasil Tes Pasien [CREATE]
def createHasilTesPasien(request):
    if (request.method == "POST"):
        return addHasilTesPasien(request)
    else:
        return formHasilTesPasien(request)

# 21. Hasil Tes Pasien [CREATE] [GET]
def formHasilTesPasien(request):
    context = {
        'listPasien': getListPasien()
    }
    return render(request, 'form_hasil_tes.html', context)

# 21. Hasil Tes Pasien [CREATE] [POST]
def addHasilTesPasien(request):
    data = request.POST
    nik = data['pasien']
    tanggal = data['tanggal']
    tipe = data['tipe']
    status = data['status']
    nilaict = '-' if data['nilaict'] == '' else data['nilaict']
    
    if (tanggal == '') or (nilaict == '-' and tipe == 'PCR'):
        messages.error(request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu.')
        return redirect('trigger6:createHasilTesPasien')
    else:
        createHasilTesPasienOlehDokter(nik, tanggal, tipe, status, nilaict)
        return redirect('trigger6:listHasilTesPasien')

trigger6/templates/detail_transaksi_hotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<style>
		body {
			counter-reset: Serial;           /* Set the Serial counter to 0 */
		}
	
		#num:before {
			counter-increment: Serial;      /* Increment the Serial counter */
			content: counter(Serial); /* Display the counter */
		}
	  </style>
{% endblock %}

{% block title %} Detail Transaksi Hotel {% endblock %}

{% block body %}
<h1 class="m-3"> Detail Transaksi Hotel </h1>

<div class="card m-3">
	<h3 class="card-header"> Data Transaksi </h3>
    <ul class="list-group list-group-flush">
		<li class="list-group-item"> NIK Pasien: {{ data.kodepasien }}</li>
        <li class="list-group-item"> Id Transaksi: {{ data.idtransaksi }}</li>
        <li class="list-group-item"> Tanggal Pembayaran: {{ data.tanggalpembayaran }}</li>
        <li class="list-group-item"> Waktu Pembayaran: {{ data.waktupembayaran }}</li>
        <li class="list-group-item"> Total Biaya: {{ data.totalbayar }}</li>
        <li class="list-group-item"> Status Bayar: {{ data.statusbayar }}</li>
    </ul>
	
	<h3 class="card-header"> Rincian Bayar </h3>
	<ul class="list-group list-group-flush">
		<li class="list-group-item"> Transaksi Booking: {{ booking.totalbayar }} </li>
		{% for makan in listMakan %}
			<li class="list-group-item"> Transaksi Makan <span id="num"></span>: {{ makan.totalbayar }} </li>
		{% endfor %}
	</ul>

	<h3 class="card-header"> Data Reservasi </h3>
	<ul class="list-group list-group-flush">
		<li class="list-group-item"> Tanggal Masuk: {{ data.tglmasuk }} </li>
		<li class="list-group-item"> Tanggal Keluar: {{ data.tglkeluar }} </li>
		<li class="list-group-item"> Hotel: {{ data.nama }} </li>
		<li class="list-group-item"> Ruangan: {{ data.koderoom }} </li>
	</ul>
	
</div>

<div class="card m-3">
	<a href="{% url 'trigger6:listTransaksiHotel' %}" type="button" class="btn btn-secondary"> KEMBALI </a>
</div>


{% endblock %}

trigger6/templates/detail_transaksi_rs.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Detail Transaksi RS {% endblock %}

{% block body %}
<h1 class="m-3"> Detail Transaksi RS </h1>

<div class="card m-3">
	<h3 class="card-header"> Data Transaksi </h3>
    <ul class="list-group list-group-flush">
		<li class="list-group-item"> NIK Pasien: {{ data.kodepasien }}</li>
        <li class="list-group-item"> Id Transaksi: {{ data.idtransaksi }}</li>
        <li class="list-group-item"> Tanggal Pembayaran: {{ data.tglpembayaran }}</li>
        <li class="list-group-item"> Waktu Pembayaran: {{ data.waktupembayaran }}</li>
        <li class="list-group-item"> Total Biaya: {{ data.totalbiaya }}</li>
        <li class="list-group-item"> Status Bayar: {{ data.status }}</li>
    </ul>
	
	<h3 class="card-header"> Data Reservasi </h3>
	<ul class="list-group list-group-flush">
		<li class="list-group-item"> Tanggal Masuk: {{ data.tglmasuk }} </li>
		<li class="list-group-item"> Tanggal Keluar: {{ data.tglkeluar }} </li>
		<li class="list-group-item"> Nama - ID Rumah Sakit: {{ data.nama }} - {{ data.kode }} </li>
		<li class="list-group-item"> Ruangan: {{ data.koderuangan }} </li>
		<li class="list-group-item"> Bed: {{ data.kodebed }} </li>
	</ul>
	
</div>

<div class="card m-3">
	<a href="{% url 'trigger6:listTransaksiRS' %}" type="button" class="btn btn-secondary"> KEMBALI </a>
</div>


{% endblock %}

trigger6/templates/form_hasil_tes.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <style>
      .hidden {
          display: none;
      }
  </style>
{% endblock %}
{% block title %} Buat Hasil Tes Pasien {% endblock %}

{% block body %}

<div class="container">
    <h1 class="text-center m-3">Buat Hasil Tes Pasien</h1>
    <p class="text--center" id="message" style="color: white;background-color: red;border-radius: 7px;">{{message}}</p>
    
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <form method="POST">
        {% csrf_token %}

        <div class="mb-3 " id="nik-form">
            <label for="pasien" class="form-label">NIK Pasien</label>
            <select  name="pasien" id="pasien" class="form-control">
                {% for pasien  in listPasien %}
                    <option value= {{ pasien.nik }}>{{ pasien.nik }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label for="tanggal" class="form-label">Tanggal Tes</label>
            <input type="date" name="tanggal" class="form-control " id="tanggal">
        </div>

        <div class="mb-3">
            <label for="tipe" class="form-label">Jenis Tes</label>
            <select onchange="changeTipe(this)" name="tipe" id="tipe" class="form-control">
                <option value="Antigen"> Antigen </option>
                <option value="PCR"> PCR </option>
            </select>
        </div>
        
        <div class="mb-3">
            <label for="status" class="form-label">Status</label>
            <select name="status" id="status" class="form-control custom-select">
                <option value="Non-Reaktif"> Non-Reaktif </option>
                <option value="Reaktif"> Reaktif </option>
            </select>
        </div>

        <div class="mb-3 hidden" id="nilaict-form">
            <label for="nilaict" class="form-label">Nilai CT</label>
            <input type="number" name="nilaict" class="form-control " id="nilaict">
        </div>

        <button type="submit" class="btn btn-success btn-block">Simpan</button>
    </form>
</div>
{% endblock  %}

{% block script %}
<script>
    function changeTipe(obj) {
        const selectedIndex = obj.selectedIndex;
        const nilaiCTForm = document.querySelector("#nilaict-form");
        if (selectedIndex === 0) {
            nilaiCTForm.classList.add("hidden");
        } else if (selectedIndex === 1) {
            nilaiCTForm.classList.remove("hidden");
        }
    }
    $('.required').prop('required', function(){
        return  $(this).is(':visible');
    });
</script>
{% endblock  %}

trigger6/templates/hasil_tes.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<style>
        body {
            counter-reset: Serial;           /* Set the Serial counter to 0 */
        }
    
        tr td:first-child:before {
            counter-increment: Serial;      /* Increment the Serial counter */
            content: counter(Serial); /* Display the counter */
        }
      </style>
{% endblock %}

{% block title %} Daftar Hasil Tes Pasien {% endblock %}

{% block body %}
<h1 class="m-3"> Daftar Hasil Tes Pasien </h1>

<table class="table table-bordered m-3">
	<thead class="thead-dark">
	  <tr>
		<th>No.</th>
		<th>NIK Pasien</th>
		<th>Tanggal Tes</th>
		<th>Jenis Tes</th>
		<th>Status</th>
		<th>Nilai CT</th>
	  </tr>
	</thead>
	<tbody>
		{% for hasil in listHasil %}
		<tr>
			<td></td>
			<td>{{ hasil.nik_pasien }}</td>
			<td>{{ hasil.tanggaltes }}</td>
			<td>{{ hasil.jenis }}</td>
			<td>{{ hasil.status }}</td>
			<td>{{ hasil.nilaict }}</td>
		</tr>
		{% endfor%}
	</tbody>
</table>
{% endblock %}

trigger6/templates/transaksi_hotel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Daftar Transaksi Hotel {% endblock %}

{% block body %}
<h1 class="m-3"> Daftar Transaksi Hotel </h1>

<table class="table table-bordered m-3">
	<thead class="thead-dark">
	  <tr>
		<th>ID Transaksi</th>
		<th>Kode Pasien</th>
		<th>Tanggal Pembayaran</th>
		<th>Waktu Pembayaran</th>
		<th>Total Biaya</th>
		<th>Status Bayar</th>
		<th>Tindakan</th>
	  </tr>
	</thead>
	<tbody>
		{% for transaksi in listTransaksi %}
		<tr>
			<td>{{ transaksi.idtransaksi }}</td>
			<td>{{ transaksi.kodepasien }}</td>
			{% if transaksi.tanggalpembayaran is none %}
				<td> - </td>
			{% else %}
				<td>{{ transaksi.tanggalpembayaran }}</td>
			{% endif %}
			{% if transaksi.waktupembayaran is none %}
				<td> - </td>
			{% else %}
				<td>{{ transaksi.waktupembayaran }}</td>
			{% endif %}
			<td>{{ transaksi.totalbayar }}</td>
			<td>{{ transaksi.statusbayar }}</td>
			<td> 
				{% if transaksi.statusbayar == "Belum Lunas" %}
					<a href="update/{{ transaksi.idtransaksi}}"> [Konfirmasi Pembayaran] </a>
				{% endif %}
				<a href="{{ transaksi.idtransaksi}}"> [Detail] </a>
			</td>
		</tr>
		{% endfor%}
	</tbody>
</table>
{% endblock %}

trigger6/templates/transaksi_rs.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block title %} Daftar Transaksi RS {% endblock %}

{% block body %}
<h1 class="m-3"> Daftar Transaksi RS </h1>

<table class="table table-bordered m-3">
	<thead class="thead-dark">
	  <tr>
		<th>ID Transaksi</th>
		<th>Kode Pasien</th>
		<th>Tanggal Pembayaran</th>
		<th>Tanggal Masuk</th>
		<th>Total Biaya</th>
		<th>Status Bayar</th>
		<th>Tindakan</th>
	  </tr>
	</thead>
	<tbody>
		{% for transaksi in listTransaksi %}
		<tr>
			<td>{{ transaksi.idtransaksi }}</td>
			<td>{{ transaksi.kodepasien }}</td>
			{% if transaksi.tglpembayaran is none %}
				<td> - </td>
			{% else %}
				<td>{{ transaksi.tglpembayaran }}</td>
			{% endif %}
			<td>{{ transaksi.tglmasuk }}</td>
			<td>{{ transaksi.totalbiaya }}</td>
			<td>{{ transaksi.statusbayar }}</td>
			<td> 
				{% if transaksi.statusbayar == "Belum Lunas" %}
					<a href="update/{{ transaksi.idtransaksi}}"> [Konfirmasi Pembayaran] </a>
				{% endif %}
				<a href="{{ transaksi.idtransaksi}}"> [Detail] </a>
			</td>
		</tr>
		{% endfor%}
	</tbody>
</table>
{% endblock %}